#!/bin/sh


# Change your keymap:
xmodmap "/home/miroslav/.Xmodmap"


# start applications and utilities
compton &
tint2 &
nm-applet &
volumeicon &
nitrogen --restore

eval $(ssh-agent)


# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &


# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi


# exec fluxbox -log "/home/miroslav/.fluxbox/log"
exec fluxbox
